# Generated by Django 2.0.4 on 2018-05-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rising', models.DateTimeField(blank=True)),
                ('lowering', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledEbb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rising', models.TimeField(blank=True)),
                ('log_rising_date', models.DateField(blank=True)),
                ('duration', models.DurationField()),
                ('interval', models.DurationField()),
                ('job_id', models.UUIDField()),
                ('state', models.CharField(choices=[('NO', 'NONE'), ('QU', 'Queued'), ('RI', 'Rising'), ('LO', 'Lowering')], default='NO', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('temperature', models.FloatField()),
            ],
        ),
    ]
