# Generated by Django 2.0.4 on 2018-05-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaponie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bac', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('level', models.FloatField()),
            ],
        ),
    ]
